version: "3.7"
services: 
  backend:
    env_file: 
      "./.env"
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./tango-def
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    links: 
      - "backend:be"


